name: Build & Release

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: npwd_advertisements
      APP_NICE_NAME: NPWD Advertisements

    steps:
      - name: Get tag
        run: echo ::set-output name=VERSION_TAG::${GITHUB_REF/refs\/tags\//}
        id: get_tag

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & Build
        run: yarn --frozen-lockfile && yarn build

      - name: Build game scripts
        run: yarn build:game

      - name: Bundle
        run: |
          mkdir -p ./temp/${{env.APP_NAME}}
          cp ./{README.md,fxmanifest.lua} ./temp/${{env.APP_NAME}}
          cp -r ./dist ./temp/${{env.APP_NAME}}
          cp -r ./web ./temp/${{env.APP_NAME}}
          cd ./temp && zip -r ../${{env.APP_NAME}}.zip ./${{env.APP_NAME}}
      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: ${{env.APP_NICE_NAME}} | ${{ steps.get_tag.outputs.VERSION_TAG }}
          prerelease: false
          files: ${{env.APP_NAME}}.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
