QBShared = QBShared or {}
QBShared.Vehicles = QBShared.Vehicles or {}

local Vehicles = {
    --- PDM (0)
    {model = 'asbo', name = 'Asbo', brand = 'Maxwell', price = 4000, category = 'Compacts',      type = 'automobile', shop = 'luxury'},

    {model = 'amdbx', name = 'Aston Martin DBX Carbon Edition', brand = 'aston', price = 24000, category = 'aston',      type = 'automobile', shop = 'buy'},
    {model = 'ast', name = '2013 Aston Martin Vanquish', brand = 'aston', price = 24000, category = 'aston',      type = 'automobile', shop = 'buy'},
    {model = 'tltypes', name = 'Acura TL Type-S', brand = 'aston', price = 24000, category = 'aston',      type = 'automobile', shop = 'luxury'},

    {model = 'aaq4', name = '2017 Audi A4 Quattro ABT', brand = 'audi', price = 46000, category = 'audi',      type = 'automobile', shop = 'pdm'},
    {model = 'q820', name = '2020 Audi Q8 50TDI', brand = 'audi', price = 52000, category = 'audi',      type = 'automobile', shop = 'pdm'},
    {model = 'r820', name = '2020 Audi R8', brand = 'audi', price = 68000, category = 'audi',      type = 'automobile', shop = 'pdm'},
    {model = 'r8ppi', name = '2013 Audi R8 V10', brand = 'audi', price = 69000, category = 'audi',      type = 'automobile', shop = 'pdm'},
    {model = 'rs6', name = '2016 Audi RS6 C7', brand = 'audi', price = 55000, category = 'audi',      type = 'automobile', shop = 'pdm'},
    {model = 'rs72020', name = '2020 Audi RS7', brand = 'audi', price = 59000, category = 'audi',      type = 'automobile', shop = 'pdm'},
    {model = 'sq72016', name = '2016 Audi SQ7', brand = 'audi', price = 50000, category = 'audi',      type = 'automobile', shop = 'buy'},
    {model = 'ttrs', name = '2010 Audi TT RS', brand = 'audi', price = 48000, category = 'audi',      type = 'automobile', shop = 'pdm'},

    {model = 'bbentayga', name = 'Bentley Bentayga', brand = 'bentley', price = 12000, category = 'bentley',      type = 'automobile', shop = 'pdm'},
    {model = 'cgts', name = '2020 Bentley Continental GT Convertible', brand = 'bentley', price = 125000, category = 'bentley',      type = 'automobile', shop = 'pdm'},

    {model = '760li04', name = '2004 BMW 760Li Individual (E66/PFL)', brand = 'bmw', price = 25000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'bmci', name = '2018 BMW M5 F90', brand = 'bmw', price = 38000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'i8', name = '2015 BMW i8 (I12)', brand = 'bmw', price = 39000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'm2', name = '2016 BMW M2', brand = 'bmw', price = 35000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'm3e36', name = '1997 BMW M3 E36', brand = 'bmw', price = 18000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'm3e92', name = '2008 BMW M3 e92', brand = 'bmw', price = 20000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'm3f80', name = '2015 BMW M3 (F80)', brand = 'bmw', price = 33000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'm4f82', name = '2015 BMW M4 F82', brand = 'bmw', price = 36000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'm6f13', name = 'BMW M6 F13 Shadow Line', brand = 'bmw', price = 39000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'x6m', name = 'BMW X6M F16', brand = 'bmw', price = 40000, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'z419', name = '2019 BMW Z4 M40i', brand = 'bmw', price = 34500, category = 'bmw',      type = 'automobile', shop = 'pdm'},
    {model = 'm3g80', name = 'BMW M3 G80 2022', brand = 'bmw', price = 41000, category = 'bmw',      type = 'automobile', shop = 'pdm'},

    {model = 'bolide', name = '2020 Bugatti Bolide', brand = 'bugatti', price = 2400000, category = 'bugatti',      type = 'automobile', shop = 'luxury'},

    {model = 'cats', name = '2016 Cadillac ATS-V Coupe', brand = 'cadillac', price = 61000, category = 'cadillac',      type = 'automobile', shop = 'pdm'},
    {model = 'cesc21', name = '2021 Cadillac Escalade', brand = 'cadillac', price = 66000, category = 'cadillac',      type = 'automobile', shop = 'pdm'},

    {model = '09tahoe', name = '2009 Chevrolet Tahoe', brand = 'chevrolet', price = 38000, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = '15tahoe', name = '2015 Chevrolet Tahoe', brand = 'chevrolet', price = 46000, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = '2020ss', name = '2020 Chevrolet Camaro SS', brand = 'chevrolet', price = 51000, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = 'c7', name = '2014 Chevrolet Corvette C7 Stingray', brand = 'chevrolet', price = 49000, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = 'camrs17', name = '2017 Chevrolet Camaro RS', brand = 'chevrolet', price = 48000, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = 'corvettec5z06', name = 'Chevrolet Corvette C5 Z06', brand = 'chevrolet', price = 39500, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = 'czr1', name = '2009 Chevrolet Corvette ZR1', brand = 'chevrolet', price = 29000, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = 'stingray', name = '2020 Chevrolet Corvette C8 Stingray', brand = 'chevrolet', price = 53500, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},
    {model = 'tahoe21', name = '2021 Chevrolet Tahoe RST', brand = 'chevrolet', price = 59000, category = 'chevrolet',      type = 'automobile', shop = 'pdm'},

    {model = '1310', name = 'Dacia 1310 2001', brand = 'dacia', price = 16000, category = 'dacia',      type = 'automobile', shop = 'pdm'},
    {model = 'cutlass', name = 'Dacia logan pickup ', brand = 'dacia', price = 19000, category = 'dacia',      type = 'automobile', shop = 'pdm'},
    {model = 'logan', name = '2008 Dacia Logan', brand = 'dacia', price = 14000, category = 'dacia',      type = 'automobile', shop = 'pdm'},
    {model = 'sandero', name = 'Dacia Sandero 2014', brand = 'dacia', price = 9500, category = 'dacia',      type = 'automobile', shop = 'pdm'},
    {model = 'stepway', name = 'Dacia Sandero Stepway 2014', brand = 'dacia', price = 11500, category = 'dacia',      type = 'automobile', shop = 'pdm'},

    {model = '16challenger', name = '2016 Dodge Challenger', brand = 'dodge', price = 56000, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = '16charger', name = '2016 Dodge Charger', brand = 'dodge', price = 57500, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = '99viper', name = '1999 Dodge Viper GTS ACR', brand = 'dodge', price = 9550, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = 'chr20', name = 'Dodge Charger Hellcat Widebody 2021', brand = 'dodge', price = 61500, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = 'demon', name = '2018 Dodge Challenger SRT Demon', brand = 'dodge', price = 57000, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = 'raid', name = 'Dodge Challenger Raid', brand = 'dodge', price = 48000, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = 'ram2500', name = '2015 Dodge RAM 2500', brand = 'dodge', price = 61500, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = 'srt4', name = 'Dodge Neon SRT-4', brand = 'dodge', price = 28500, category = 'dodge',      type = 'automobile', shop = 'pdm'},
    {model = 'trx', name = '2017 Dodge RAM 1500 Rebel TRX', brand = 'dodge', price = 71500, category = 'dodge',      type = 'automobile', shop = 'pdm'},

    {model = '488', name = 'Ferrari 488 Spider', brand = 'ferrari', price = 125000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'f430s', name = 'Ferrari F430 Scuderia', brand = 'ferrari', price = 205000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'f812', name = '2018 Ferrari 812 Superfast', brand = 'ferrari', price = 135000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'fct', name = '2015 Ferrari California T', brand = 'ferrari', price = 148000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'fxxk', name = 'Ferrari FXX-K Hybrid Hypercar', brand = 'ferrari', price = 325000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'laferrari', name = '2015 Ferrari LaFerrari', brand = 'ferrari', price = 295000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'mig', name = 'Ferrari Enzo', brand = 'ferrari', price = 135000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'yFe458i1', name = '458 Italia', brand = 'ferrari', price = 151000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'yFe458i2', name = '458 Speciale', brand = 'ferrari', price = 168000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'yFe458s1', name = '458 Spider', brand = 'ferrari', price = 164000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'yFe458s2', name = '458 Speciale Aperta', brand = 'ferrari', price = 165000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'yFeF12A', name = 'Ferrari F60 America', brand = 'ferrari', price = 209000, category = 'ferrari',      type = 'automobile', shop = 'luxury'},
    {model = 'yFeF12T', name = 'Ferrari F12 TRS Roadster', brand = 'ferrari', price = 200500, category = 'ferrari',      type = 'automobile', shop = 'luxury'},

    {model = 'f150', name = '2012 Ford F150 SVT Raptor R', brand = 'ford', price = 68000, category = 'ford',      type = 'automobile', shop = 'pdm'},
    {model = 'fgt', name = '2005 Ford GT', brand = 'ford', price = 48000, category = 'ford',      type = 'automobile', shop = 'pdm'},
    {model = 'gt17', name = '2017 Ford GT', brand = 'ford', price = 61000, category = 'ford',      type = 'automobile', shop = 'pdm'},
    {model = 'raptor2017', name = '2017 Ford Raptor', brand = 'ford', price = 91500, category = 'ford',      type = 'automobile', shop = 'pdm'},
    {model = 'wildtrak', name = '2021 Ford Bronco Wildtrak', brand = 'ford', price = 65000, category = 'ford',      type = 'automobile', shop = 'pdm'},

    {model = 'ap2', name = 'Honda S2000 AP2', brand = 'honda', price = 38000, category = 'honda',      type = 'automobile', shop = 'pdm'},
    {model = 'fk8', name = '2018 Honda Civic Type-R (FK8)', brand = 'honda', price = 41000, category = 'honda',      type = 'automobile', shop = 'pdm'},
    {model = 'honcrx91', name = 'Honda CRX SiR 1991', brand = 'honda', price = 13500, category = 'honda',      type = 'automobile', shop = 'pdm'},
    {model = 'na1', name = '1992 Honda NSX-R (NA1)', brand = 'honda', price = 21500, category = 'honda',      type = 'automobile', shop = 'pdm'},

    {model = 'it18', name = '2017 Italdesign Zerouno', brand = 'italdesign', price = 1200000, category = 'italdesign',      type = 'automobile', shop = 'luxury'},

    {model = 'fpacehm', name = 'Jaguar F-pace 2017 Hamann Edition', brand = 'jaguar', price = 68250, category = 'jaguar',      type = 'automobile', shop = 'luxury'},

    {model = 'jeep2012', name = '2012 Jeep Wrangler', brand = 'jeep', price = 38750, category = 'jeep',      type = 'automobile', shop = 'pdm'},
    {model = 'jeepreneg', name = 'Jeep Renegade', brand = 'jeep', price = 36500, category = 'jeep',      type = 'automobile', shop = 'pdm'},
    {model = 'srt8', name = '2015 Jeep SRT-8', brand = 'jeep', price = 42250, category = 'jeep',      type = 'automobile', shop = 'pdm'},
    {model = 'trhawk', name = '2018 Jeep Grand Cherokee', brand = 'jeep', price = 58950, category = 'jeep',      type = 'automobile', shop = 'pdm'},

    {model = 'agerars', name = '2017 Koenigsegg Agera RS', brand = 'koenigsegg', price = 950000, category = 'koenigsegg',      type = 'automobile', shop = 'luxury'},
    {model = 'regera', name = 'Koenigsegg Regera', brand = 'koenigsegg', price = 1100000, category = 'koenigsegg',      type = 'automobile', shop = 'buy'},

    {model = 'huracanst', name = 'Lamborghini Huracan Super Trofeo', brand = 'lamborghini', price = 650000, category = 'lamborghini',      type = 'automobile', shop = 'luxury'},
    {model = 'lambose', name = 'Lamborghini Sesto Elemento', brand = 'lamborghini', price = 370000, category = 'lamborghini',      type = 'automobile', shop = 'luxury'},
    {model = 'lp670sv', name = '2009 Lamborghini Murcielago LP 670-4 SV', brand = 'lamborghini', price = 420000, category = 'lamborghini',      type = 'automobile', shop = 'luxury'},
    {model = 'lp700r', name = '2013 Lamborghini Aventador LP700-4 Roadster', brand = 'lamborghini', price = 390000, category = 'lamborghini',      type = 'automobile', shop = 'luxury'},
    {model = 'svj63', name = 'Lamborghini Aventador SVJ', brand = 'lamborghini', price = 412000, category = 'lamborghini',      type = 'automobile', shop = 'luxury'},
    {model = 'urus', name = 'Lamborghini Urus', brand = 'lamborghini', price = 360000, category = 'lamborghini',      type = 'automobile', shop = 'buy'},
    {model = 'veneno', name = 'Lamborghini Veneno', brand = 'lamborghini', price = 380000, category = 'lamborghini',      type = 'automobile', shop = 'luxury'},

    {model = 'lrrr', name = '1973 Land Rover Range Rover', brand = 'landrover', price = 36000, category = 'landrover',      type = 'automobile', shop = 'pdm'},

    {model = 'gs350', name = 'Lexus GS 350', brand = 'lexus', price = 38000, category = 'lexus',      type = 'automobile', shop = 'pdm'},
    {model = 'is350mod', name = '2014 Lexus IS 350', brand = 'lexus', price = 36500, category = 'lexus',      type = 'automobile', shop = 'pdm'},
    {model = 'rcf', name = '2015 Lexus RCF', brand = 'lexus', price = 38500, category = 'lexus',      type = 'automobile', shop = 'pdm'},

    {model = 'esprit02', name = '2002 Lotus Esprit V8', brand = 'lotus', price = 41000, category = 'lotus',      type = 'automobile', shop = 'pdm'},

    {model = 'levante', name = 'Maserati Levante', brand = 'maserati', price = 75000, category = 'maserati',      type = 'automobile', shop = 'luxury'},

    {model = '84rx7k', name = '1984 Mazda RX-7 Stanced Version', brand = 'mazda', price = 39750, category = 'mazda',      type = 'automobile', shop = 'pdm'},
    {model = 'dragfd', name = '2002 Mazda RX-7 FD Drag', brand = 'mazda', price = 43250, category = 'mazda',      type = 'automobile', shop = 'pdm'},
    {model = 'fc3s', name = 'Mazda RX7 FC3S', brand = 'mazda', price = 21000, category = 'mazda',      type = 'automobile', shop = 'pdm'},
    {model = 'majfd', name = 'Mazda RX-7 FD', brand = 'mazda', price = 26750, category = 'mazda',      type = 'automobile', shop = 'pdm'},
    {model = 'miata3', name = '1989 Mazda Miata NA', brand = 'mazda', price = 25250, category = 'mazda',      type = 'automobile', shop = 'pdm'},
    {model = 'na6', name = 'Mazda MX-5 Miata (NA6C)', brand = 'mazda', price = 18500, category = 'mazda',      type = 'automobile', shop = 'pdm'},

    {model = '650s', name = 'McLaren 650S Coupe', brand = 'mclaren', price = 380000, category = 'mclaren',      type = 'automobile', shop = 'luxury'},
    {model = '675lt', name = '2016 McLaren 675LT Coupe', brand = 'mclaren', price = 401000, category = 'mclaren',      type = 'automobile', shop = 'buy'},
    {model = '720s', name = '2017 McLaren 720S', brand = 'mclaren', price = 423850, category = 'mclaren',      type = 'automobile', shop = 'luxury'},
    {model = 'gtr96', name = '1996 McLaren F1 GTR', brand = 'mclaren', price = 268000, category = 'mclaren',      type = 'automobile', shop = 'luxury'},
    {model = 'mcst', name = '2020 McLaren Speedtail', brand = 'mclaren', price = 465000, category = 'mclaren',      type = 'automobile', shop = 'luxury'},
    {model = 'mp412c', name = 'McLaren MP4-12C', brand = 'mclaren', price = 348000, category = 'mclaren',      type = 'automobile', shop = 'luxury'},
    {model = 'senna', name = '2019 McLaren Senna', brand = 'mclaren', price = 415000, category = 'mclaren',      type = 'automobile', shop = 'luxury'},

    {model = 'c6320', name = '2020 Mercedes-AMG C63s', brand = 'mercedesamg', price = 75250, category = 'mercedesbenz',      type = 'automobile', shop = 'pdm'},
    {model = 'G65', name = '2013 Mercedes-Benz G65 AMG', brand = 'mercedesbenz', price = 9999999, category = 'mercedesbenz',      type = 'automobile', shop = 'buy'},
    {model = 'amggtrr20', name = '2020 Mercedes-Benz AMG GT-R Roadster', brand = 'mercedesbenz', price = 158000, category = 'mercedesbenz',      type = 'automobile', shop = 'luxury'},
    {model = 'e400', name = '2019 Mercedes-Benz E400 Coupe 4matic (C238)', brand = 'mercedesbenz', price = 51500, category = 'mercedesbenz',      type = 'automobile', shop = 'pdm'},
    {model = 'gl63', name = 'Mercedes-Benz GL63 AMG', brand = 'mercedesbenz', price = 53750, category = 'mercedesbenz',      type = 'automobile', shop = 'luxury'},
    {model = 'mbc63', name = '2012 Mercedes-Benz C63 AMG Coupe Black Series', brand = 'mercedesbenz', price = 48950, category = 'mercedesbenz',      type = 'automobile', shop = 'pdm'},
    {model = 's500w222', name = '2014 Mercedes-Benz S500 W222', brand = 'mercedesbenz', price = 43250, category = 'mercedesbenz',      type = 'automobile', shop = 'pdm'},
    {model = 'sl500', name = '1995 Mercedes-Benz SL500', brand = 'mercedesbenz', price = 36000, category = 'mercedesbenz',      type = 'automobile', shop = 'pdm'},
    {model = 'v250', name = 'Mercedes-Benz V-class 250 Bluetec LWB', brand = 'mercedesbenz', price = 38000, category = 'mercedesbenz',      type = 'automobile', shop = 'pdm'},
    {model = 'feltzer2', name = 'Mercedes-Benz AMG DTM C204', brand = 'mercedesbenz', price = 148000, category = 'mercedesbenz',      type = 'automobile', shop = 'luxury'},

    {model = 'cp9a', name = 'Mitsubishi Lancer Evo VI T.M.E (CP9A)', brand = 'mitsubishi', price = 32000, category = 'mitsubishi',      type = 'automobile', shop = 'pdm'},
    {model = 'fto', name = 'Mitsubishi FTO GP Version-R', brand = 'mitsubishi', price = 40000, category = 'mitsubishi',      type = 'automobile', shop = 'pdm'},

    {model = '180sx', name = 'Nissan 180SX Type-X', brand = 'nissan', price = 38000, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'Safari97', name = '1997 Nissan Patrol Super Safari Y60', brand = 'nissan', price = 26000, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'gtr', name = '2017 Nissan GTR', brand = 'nissan', price = 78000, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'gtrc', name = '2017 R35 Nissan GTR Convertible', brand = 'nissan', price = 81000, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'maj350', name = 'Nissan Fairlady Z Z33', brand = 'nissan', price = 45000, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'nis15', name = 'Nissan Silvia S15 Spec-R', brand = 'nissan', price = 31500, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'nissantitan17', name = '2017 Nissan Titan Warrior', brand = 'nissan', price = 83000, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'ns350', name = 'Nissan 350z Stardast', brand = 'nissan', price = 58200, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'nzp', name = 'Nissan 370z Pandem', brand = 'nissan', price = 49500, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 's14', name = '1998 Nissan Silvia K', brand = 'nissan', price = 17950, category = 'nissan',      type = 'automobile', shop = 'pdm'},
    {model = 'skyline', name = 'Nissan Skyline GT-R (BNR34)', brand = 'nissan', price = 39500, category = 'nissan',      type = 'automobile', shop = 'pdm'},

    {model = 'yPG205t16A', name = 'Peugeot 205 Rally', brand = 'peugeot', price = 49500, category = 'peugeot',      type = 'automobile', shop = 'pdm'},
    {model = 'yPG205t16B', name = 'Peugeot 205 Turbo 16', brand = 'peugeot', price = 45000, category = 'peugeot',      type = 'automobile', shop = 'pdm'},
    {model = '208gti21', name = 'Peugeot 208 GTI 2021', brand = 'peugeot', price = 58000, category = 'peugeot',      type = 'automobile', shop = 'buy'},

    {model = '718caymans', name = 'Porsche 718 Cayman S', brand = 'porsche', price = 68000, category = 'porsche',      type = 'automobile', shop = 'luxury'},
    {model = 'cgt', name = '2003 Porsche Carrera GT (980)', brand = 'porsche', price = 69500, category = 'porsche',      type = 'automobile', shop = 'luxury'},
    {model = 'maj935', name = '1978 Porsche 935 Moby Dick', brand = 'porsche', price = 125000, category = 'porsche',      type = 'automobile', shop = 'luxury'},
    {model = 'pcs18', name = '2018 Porsche Cayenne S', brand = 'porsche', price = 69750, category = 'porsche',      type = 'automobile', shop = 'luxury'},
    {model = 'pm19', name = '2019 Porsche Macan Turbo', brand = 'porsche', price = 71500, category = 'porsche',      type = 'automobile', shop = 'luxury'},
    {model = 'taycan', name = '2020 Porsche Taycan Turbo S', brand = 'porsche', price = 70250, category = 'porsche',      type = 'automobile', shop = 'luxury'},

    {model = 'regalia', name = 'Quartz Regalia 723', brand = 'quartz', price = 175000, category = 'quartz',      type = 'automobile', shop = 'luxury'},

    {model = 'rrevoque', name = 'Range Rover Evoque', brand = 'rangerover', price = 65000, category = 'rangerover',      type = 'automobile', shop = 'luxury'},
    {model = 'rrst', name = 'Range Rover Vogue Startech', brand = 'rangerover', price = 71000, category = 'rangerover',      type = 'automobile', shop = 'luxury'},
    {model = 'rsvr16', name = '2016 Range Rover Sport SVR', brand = 'rangerover', price = 115000, category = 'rangerover',      type = 'automobile', shop = 'luxury'},

    {model = 'twingo', name = 'Renault Twingo I', brand = 'renault', price = 18000, category = 'renault',      type = 'automobile', shop = 'pdm'},

    {model = 'dawnonyx', name = '2016 Rolls-Royce Dawn Onyx', brand = 'rollsroyce', price = 154250, category = 'rollsroyce',      type = 'automobile', shop = 'luxury'},
    {model = 'rculi', name = 'Rolls Royce Cullinan', brand = 'rollsroyce', price = 131500, category = 'rollsroyce',      type = 'automobile', shop = 'luxury'},
    {model = 'rrphantom', name = '2018 Rolls-Royce Phantom VIII', brand = 'rollsroyce', price = 124250, category = 'rollsroyce',      type = 'automobile', shop = 'luxury'},
    {model = 'wraith', name = 'Rolls-Royce Wraith', brand = 'rollsroyce', price = 129750, category = 'rollsroyce',      type = 'automobile', shop = 'luxury'},

    {model = 'subisti08', name = '2008 Subaru WRX STi', brand = 'subaru', price = 39500, category = 'subaru',      type = 'automobile', shop = 'pdm'},
    {model = 'subwrx', name = '2004 Subaru Impreza WRX STI', brand = 'subaru', price = 58650, category = 'subaru',      type = 'automobile', shop = 'pdm'},
    {model = 'svx', name = '1996 Subaru Alcyone SVX', brand = 'subaru', price = 35000, category = 'subaru',      type = 'automobile', shop = 'pdm'},

    {model = 'gsxr19', name = '2019 Suzuki GSX-R1000R', brand = 'suzuki', price = 28000, category = 'suzuki',      type = 'automobile', shop = 'pdm'},
    {model = 'katana', name = '2019 Suzuki Katana', brand = 'suzuki', price = 35000, category = 'suzuki',      type = 'automobile', shop = 'motor'},

    {model = 'models', name = '2016 Tesla Model S P90D', brand = 'tesla', price = 49500, category = 'tesla',      type = 'automobile', shop = 'pdm'},
    {model = 'p90d', name = 'Tesla Model X Performance', brand = 'tesla', price = 61500, category = 'tesla',      type = 'automobile', shop = 'pdm'},
    {model = 'teslapd', name = '2017 Tesla Model S', brand = 'tesla', price = 40000, category = 'tesla',      type = 'automobile', shop = 'pdm'},
    {model = 'teslax', name = '2016 Tesla Model X P90D', brand = 'tesla', price = 59500, category = 'tesla',      type = 'automobile', shop = 'pdm'},
    {model = 'tmodel', name = '2018 Tesla Model 3', brand = 'tesla', price = 36500, category = 'tesla',      type = 'automobile', shop = 'pdm'},
    {model = 'tr22', name = '2020 Tesla Roadster', brand = 'tesla', price = 46250, category = 'tesla',      type = 'automobile', shop = 'pdm'},

    {model = 'cam8tun', name = '2018 Toyota Camry XSE', brand = 'toyota', price = 70000, category = 'toyota',      type = 'automobile', shop = 'pdm'},
    {model = 'mk2100', name = 'Toyota Mark II JZX100', brand = 'toyota', price = 90000, category = 'toyota',      type = 'automobile', shop = 'pdm'},
    {model = 'toysupmk4', name = '1998 Toyota Supra Turbo (A80)', brand = 'toyota', price = 255000, category = 'toyota',      type = 'automobile', shop = 'pdm'},
    {model = 'vxr', name = '2016 Toyota Land Cruiser VXR', brand = 'toyota', price = 900000, category = 'toyota',      type = 'automobile', shop = 'pdm'},

    {model = 'amarok', name = '2018 Volkswagen Amarok V6', brand = 'volkswagen', price = 34250, category = 'volkswagen',      type = 'automobile', shop = 'pdm'},
    {model = 'golfgti7', name = '2015 Volkswagen Golf GTI MK7', brand = 'volkswagen', price = 31500, category = 'volkswagen',      type = 'automobile', shop = 'pdm'},
    {model = 'passat', name = '2016 Volkswagen Passat B8', brand = 'volkswagen', price = 29500, category = 'volkswagen',      type = 'automobile', shop = 'pdm'},
    {model = 'vwr', name = 'Volkswagen Scirocco R 2011', brand = 'volkswagen', price = 43500, category = 'volkswagen',      type = 'automobile', shop = 'pdm'},

    {model = 'xc90', name = 'Volvo XC90 T8', brand = 'volvo', price = 43750, category = 'volvo',      type = 'automobile', shop = 'pdm'},

    {model = 'lykan', name = 'W-Motors Lykan HyperSport', brand = 'wmotors', price = 2500000, category = 'wmotors',      type = 'automobile', shop = 'pdm'},
    {model = 'wmfenyr', name = 'W-Motors Fenyr Supersport', brand = 'wmotors', price = 954000, category = 'wmotors',      type = 'automobile', shop = 'pdm'},

    --- LUXURY (0)  
    --- Industrial (10)
    { model = 'guardian',      name = 'Guardian',                      brand = 'Vapid',           price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'mixer2',        name = 'Mixer II',                      brand = 'HVY',             price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'tiptruck2',     name = 'Tipper II',                     brand = 'Brute',           price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'tiptruck',      name = 'Tipper',                        brand = 'Brute',           price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'rubble',        name = 'Rubble',                        brand = 'Jobuilt',         price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'mixer',         name = 'Mixer',                         brand = 'HVY',             price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'flatbed',       name = 'ANWB Flatbed',                 brand = 'ANWB',             price = 0,       category = 'anwb',           type = 'automobile', shop = 'truck' },
    { model = 'sheriff',       name = 'ANWB VW bus',                  brand = 'ANWB',             price = 0,       category = 'anwb',           type = 'automobile', shop = 'truck' },
    { model = 'dump',          name = 'Dump Truck',                    brand = 'HVY',             price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'bulldozer',     name = 'Dozer',                         brand = 'HVY',             price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'handler',       name = 'Dock Handler',                  brand = 'HVY',             price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    { model = 'cutter',        name = 'Cutter',                        brand = 'HVY',             price = 30000,   category = 'industrial',     type = 'automobile', shop = 'none' },
    --- Utility (11)
    { model = 'slamtruck',     name = 'Slam Truck',                    brand = 'Vapid',           price = 100000,  category = 'utility',        type = 'automobile', shop = 'none' },
    { model = 'caddy3',        name = 'Caddy (Bunker)',                brand = 'Nagasaki',        price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'caddy2',        name = 'Caddy (Civilian)',              brand = 'Nagasaki',        price = 12000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'caddy3',        name = 'Caddy (Golf)',                  brand = 'Nagasaki',        price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'utillitruck',   name = 'Utility Truck (Cherry Picker)', brand = 'Brute',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'utillitruck2',  name = 'Utility Truck (Van)',           brand = 'Brute',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'utillitruck3',  name = 'Utility Truck (Contender)',     brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'tractor',       name = 'Tractor',                       brand = 'Stanley',         price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'tractor2',      name = 'Fieldmaster',                   brand = 'Stanley',         price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'tractor3',      name = 'Fieldmaster',                   brand = 'Stanley',         price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'towtruck',      name = 'Tow Truck (Large)',             brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'none' },
    { model = 'towtruck2',     name = 'Tow Truck (Small)',             brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'none' },
    { model = 'scrap',         name = 'Scrap Truck',                   brand = 'Vapid',           price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'sadler',        name = 'Sadler',                        brand = 'Vapid',           price = 20000,   category = 'utility',        type = 'automobile', shop = 'none' },
    { model = 'ripley',        name = 'Ripley',                        brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'mower',         name = 'Lawn Mower',                    brand = 'Jacksheepe',      price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'forklift',      name = 'Forklift',                      brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'docktug',       name = 'Docktug',                       brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'airtug',        name = 'Airtug',                        brand = 'HVY',             price = 30000,   category = 'utility',        type = 'automobile', shop = 'truck' },
    { model = 'anwbflatbed2',  name = 'ANWB Flatbed',                  brand = 'ANWB',            price = 30000,   category = 'utility',        type = 'automobile', shop = 'none' },
    --- Vans (12)
    { model = 'bison',         name = 'Bison',                         brand = 'Bravado',         price = 18000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'bobcatxl',      name = 'Bobcat XL Open',                brand = 'Vapid',           price = 13500,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'burrito3',      name = 'Burrito',                       brand = 'Declasse',        price = 4000,    category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'gburrito2',     name = 'Burrito Custom',                brand = 'Declasse',        price = 11500,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'rumpo',         name = 'Rumpo',                         brand = 'Bravado',         price = 9000,    category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'journey',       name = 'Journey',                       brand = 'Zirconium',       price = 6500,    category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'minivan',       name = 'Minivan',                       brand = 'Vapid',           price = 7000,    category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'minivan2',      name = 'Minivan Custom',                brand = 'Vapid',           price = 10000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'paradise',      name = 'Paradise',                      brand = 'Bravado',         price = 9000,    category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'rumpo3',        name = 'Rumpo Custom',                  brand = 'Bravado',         price = 19500,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'speedo',        name = 'Speedo',                        brand = 'Vapid',           price = 10000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'speedo4',       name = 'Speedo Custom',                 brand = 'Vapid',           price = 15000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'surfer',        name = 'Surfer',                        brand = 'BF',              price = 9000,    category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'youga3',        name = 'Youga Classic 4x4',             brand = 'Bravado',         price = 15000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'youga',         name = 'Youga',                         brand = 'Bravado',         price = 8000,    category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'youga2',        name = 'Youga Classic',                 brand = 'Bravado',         price = 14500,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'youga4',        name = 'Youga Custom',                  brand = 'Bravado',         price = 85000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'moonbeam',      name = 'Moonbeam',                      brand = 'Declasse',        price = 13000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'moonbeam2',     name = 'Moonbeam Custom',               brand = 'Declasse',        price = 15000,   category = 'vans',           type = 'automobile', shop = 'None' },
    { model = 'boxville',      name = 'Boxville LSDWP',                brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'truck' },
    { model = 'boxville2',     name = 'Boxville Go Postal',            brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'truck' },
    { model = 'boxville3',     name = 'Boxville Humane Labs',          brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'truck' },
    { model = 'boxville4',     name = 'Boxville Post OP',              brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'truck' },
    { model = 'boxville5',     name = 'Armored Boxville',              brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'none' },
    { model = 'pony',          name = 'Pony',                          brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'truck' },
    { model = 'pony2',         name = 'Pony (Smoke on the water)',     brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'truck' },
    { model = 'journey2',      name = 'Journey II',                    brand = 'Zirconium',       price = 7000,    category = 'vans',           type = 'automobile', shop = 'none' },
    { model = 'surfer3',       name = 'Surfer Custom',                 brand = 'BF',              price = 15000,   category = 'vans',           type = 'automobile', shop = 'none' },
    { model = 'speedo5',       name = 'Speedo Custom',                 brand = 'Vapid',           price = 238000,  category = 'vans',           type = 'automobile', shop = 'none' },
    { model = 'mule2',         name = 'Mule',                          brand = 'Maibatsu',        price = 40000,   category = 'vans',           type = 'automobile', shop = 'none' },
    { model = 'mule3',         name = 'Mule',                          brand = 'Maibatsu',        price = 40000,   category = 'vans',           type = 'automobile', shop = 'none' },
    { model = 'taco',          name = 'Taco Truck',                    brand = 'Brute',           price = 45000,   category = 'vans',           type = 'automobile', shop = 'none' },
    --- Cycles (13)
    { model = 'bmx',           name = 'BMX',                           brand = 'Fietsen',            price = 160,     category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'cruiser',       name = 'Cruiser',                       brand = 'Fietsen',            price = 510,     category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'fixter',        name = 'Fixter',                        brand = 'Fietsen',            price = 225,     category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'scorcher',      name = 'Scorcher',                      brand = 'Fietsen',            price = 280,     category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'tribike',       name = 'Whippet Race Bike',             brand = 'Fietsen',            price = 500,     category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'tribike2',      name = 'Endurex Race Bike',             brand = 'Fietsen',            price = 700,     category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'tribike3',      name = 'Tri-Cycles Race Bike',          brand = 'Fietsen',            price = 520,     category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'inductor',      name = 'Inductor',                      brand = 'Fietsen',            price = 5000,    category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    { model = 'inductor2',     name = 'Junk Energy Inductor',          brand = 'Fietsen',            price = 5000,    category = 'Fietsen',         type = 'bike',       shop = 'motor' },
    --- Boats (14)
    { model = 'dinghy4',       name = 'Weaponized Dinghy',             brand = 'Nagasaki',        price = 34500,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'avisa',         name = 'Avisa',                         brand = 'Kraken Subs',     price = 99000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'patrolboat',    name = 'Kurtz 31 Patrol Boat',          brand = 'Unknown',         price = 89000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'longfin',       name = 'Longfin',                       brand = 'Shitzu',          price = 64500,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'tug',           name = 'Tug',                           brand = 'Buckingham',      price = 125000,  category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'toro',          name = 'Toro',                          brand = 'Lampadati',       price = 71500,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'toro2',         name = 'Toro Yacht',                    brand = 'Lampadati',       price = 75000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'submersible2',  name = 'Kraken',                        brand = 'Kraken Subs',     price = 69000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'speeder',       name = 'Speeder',                       brand = 'Pegassi',         price = 59000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'speeder2',      name = 'Speeder Yacht',                 brand = 'Pegassi',         price = 61000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'tropic',        name = 'Tropic',                        brand = 'Shitzu',          price = 20000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'tropic2',       name = 'Tropic Yacht',                  brand = 'Shitzu',          price = 21000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'suntrap',       name = 'Suntrap',                       brand = 'Shitzu',          price = 19000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'submersible',   name = 'Submersible',                   brand = 'Kraken Subs',     price = 61000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'squalo',        name = 'Squalo',                        brand = 'Shitzu',          price = 41000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'seashark',      name = 'Seashark',                      brand = 'Speedophile',     price = 25000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'seashark3',     name = 'Seashark Yacht',                brand = 'Speedophile',     price = 35000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'marquis',       name = 'Marquis',                       brand = 'Dinka',           price = 50000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'jetmax',        name = 'Jetmax',                        brand = 'Shitzu',          price = 55000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'dinghy',        name = 'Dinghy 2-Seater',               brand = 'Nagasaki',        price = 29000,   category = 'boats',          type = 'boat',       shop = 'none' },
    { model = 'dinghy2',       name = 'Dinghy 4-Seater',               brand = 'Nagasaki',        price = 31000,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'dinghy3',       name = 'Dinghy (Heist)',                brand = 'Nagasaki',        price = 31500,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'dinghy4',       name = 'Dinghy Yacht',                  brand = 'Nagasaki',        price = 34500,   category = 'boats',          type = 'boat',       shop = 'boats' },
    { model = 'yaluxe',        name = 'Galaxy Super Yacht',            brand = 'Yacht',           price = 540000,  category = 'boats',          type = 'boat',       shop = 'boats' },
    --- Helicopters (15)
    { model = 'conada2',       name = 'Weaponized Conada',             brand = 'Buckingham',      price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'conada',        name = 'Conada',                        brand = 'Buckingham',      price = 115000,  category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'seasparrow2',   name = 'Sparrow',                       brand = 'Unknown',         price = 123500,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'annihilator2',  name = 'Annihilator Stealth',           brand = 'Western Company', price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'seasparrow',    name = 'Sea Sparrow',                   brand = 'Unknown',         price = 135000,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'akula',         name = 'Akula',                         brand = 'Unknown',         price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'hunter',        name = 'FH-1 Hunter',                   brand = 'Unknown',         price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'havok',         name = 'Havok',                         brand = 'Nagasaki',        price = 124750,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'volatus',       name = 'Volatus',                       brand = 'Buckingham',      price = 131500,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'supervolito2',  name = 'SuperVolito Carbon',            brand = 'Buckingham',      price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'supervolito',   name = 'SuperVolito',                   brand = 'Buckingham',      price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'swift2',        name = 'Swift Deluxe',                  brand = 'Buckingham',      price = 135000,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'valkyrie',      name = 'Valkyrie',                      brand = 'Buckingham',      price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'savage',        name = 'Savage',                        brand = 'Unknown',         price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'swift',         name = 'Swift',                         brand = 'Buckingham',      price = 123500,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'annihilator',   name = 'Annihilator',                   brand = 'Western Company', price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'cargobob2',     name = 'Cargobob Jetsam',               brand = 'Western Company', price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'skylift',       name = 'Skylift',                       brand = 'HVY',             price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'maverick',      name = 'Maverick',                      brand = 'Buckingham',      price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'frogger',       name = 'Frogger',                       brand = 'Maibatsu',        price = 115000,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'frogger2',      name = 'Frogger',                       brand = 'Maibatsu',        price = 123500,   category = 'helicopters',    type = 'heli',       shop = 'air' },
    { model = 'cargobob',      name = 'Cargobob',                      brand = 'Western Company', price = 117500,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'cargobob3',     name = 'Cargobob',                      brand = 'Western Company', price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'seasparrow3',   name = 'Sparrow (Prop)',                brand = 'Unknown',         price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'buzzard',       name = 'Buzzard Attack Chopper',        brand = 'Nagasaki',        price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    { model = 'buzzard2',      name = 'Buzzard',                       brand = 'Nagasaki',        price = 52000,   category = 'helicopters',    type = 'heli',       shop = 'none' },
    --- Planes (16)
    { model = 'streamer216',   name = 'Streamer216',                   brand = 'Mammoth',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'raiju',         name = 'F-160 Raiju',                   brand = 'Mammoth',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'alkonost',      name = 'RO-86 Alkonost',                brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'strikeforce',   name = 'B-11 Strikeforce',              brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'blimp3',        name = 'Blimp',                         brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'avenger',       name = 'Avenger',                       brand = 'Mammoth',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'avenger2',      name = 'Avenger',                       brand = 'Mammoth',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'volatol',       name = 'Volatol',                       brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'nokota',        name = 'P-45 Nokota',                   brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'seabreeze',     name = 'Seabreeze',                     brand = 'Western Company', price = 68000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'pyro',          name = 'Pyro',                          brand = 'Buckingham',      price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'mogul',         name = 'Mogul',                         brand = 'Mammoth',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'howard',        name = 'Howard NX-25',                  brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'bombushka',     name = 'RM-10 Bombushka',               brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'molotok',       name = 'V-65 Molotok',                  brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'microlight',    name = 'Ultralight',                    brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'tula',          name = 'Tula',                          brand = 'Mammoth',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'rogue',         name = 'Rogue',                         brand = 'Western Company', price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'starling',      name = 'LF-22 Starling',                brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'alphaz1',       name = 'Alpha-Z1',                      brand = 'Buckingham',      price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'nimbus',        name = 'Nimbus',                        brand = 'Buckingham',      price = 1200000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'luxor2',        name = 'Luxor Deluxe',                  brand = 'Buckingham',      price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'velum2',        name = 'Velum 5-seater',                brand = 'JoBuilt',         price = 250750,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'hydra',         name = 'Hydra',                         brand = 'Mammoth',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'blimp2',        name = 'Xero Blimp',                    brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'dodo',          name = 'Dodo',                          brand = 'Mammoth',         price = 150250,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'miljet',        name = 'Miljet',                        brand = 'Buckingham',      price = 1750000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'besra',         name = 'Besra',                         brand = 'Western Company', price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'vestra',        name = 'Vestra',                        brand = 'Buckingham',      price = 350000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'cargoplane',    name = 'Cargo Plane',                   brand = 'JoBuilt',         price = 5750000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'velum',         name = 'Velum',                         brand = 'JoBuilt',         price = 125000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'titan',         name = 'Titan',                         brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'shamal',        name = 'Shamal',                        brand = 'Buckingham',      price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'lazer',         name = 'P-996 Lazer',                   brand = 'JoBuilt',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'mammatus',      name = 'Mammatus',                      brand = 'JoBuilt',         price = 175000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'stunt',         name = 'Mallard',                       brand = 'Western Company', price = 93000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'luxor',         name = 'Luxor',                         brand = 'Buckingham',      price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'jet',           name = 'Jet',                           brand = 'Unknown',         price = 45000,   category = 'planes',         type = 'plane',      shop = 'none' },
    { model = 'duster',        name = 'Duster',                        brand = 'Western Company', price = 375000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'cuban800',      name = 'Cuban 800',                     brand = 'Western Company', price = 45000,   category = 'planes',         type = 'plane',      shop = 'air' },
    { model = 'blimp',         name = 'Atomic Blimp',                  brand = 'Unknown',         price = 165000,   category = 'planes',         type = 'plane',      shop = 'none' },
    --- Service (17)
    { model = 'brickade',      name = 'Brickade',                      brand = 'MTL',             price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'brickade2',     name = 'Brickade 6x6',                  brand = 'MTL',             price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'pbus2',         name = 'Festival Bus',                  brand = 'Unknown',         price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'wastelander',   name = 'Wastelander',                   brand = 'MTL',             price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'rallytruck',    name = 'Dune',                          brand = 'MTL',             price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'metrotrain',    name = 'Metro Train',                   brand = 'Unknown',         price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'freight',       name = 'Freight Train',                 brand = 'Unknown',         price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'cablecar',      name = 'Cable Car',                     brand = 'Unknown',         price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'trash',         name = 'Trashmaster',                   brand = 'JoBuilt',         price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'trash2',        name = 'Trashmaster',                   brand = 'JoBuilt',         price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'tourbus',       name = 'Tour Bus',                      brand = 'Brute',           price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'taxi',          name = 'Taxi',                          brand = 'Vapid',           price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'rentalbus',     name = 'Rental Shuttle Bus',            brand = 'Brute',           price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'coach',         name = 'Dashound',                      brand = 'Brute',           price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'bus',           name = 'Bus',                           brand = 'Brute',           price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    { model = 'airbus',        name = 'Airport Bus',                   brand = 'Brute',           price = 100000,  category = 'service',        type = 'automobile', shop = 'none' },
    --- Emergency (18)
    { model = 'riot',          name = 'Police Riot',                   brand = 'Brute',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'riot2',         name = 'RCV',                           brand = 'Unknown',         price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'pbus',          name = 'Police Prison Bus',             brand = 'Vapid',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police',        name = 'Kmar VW',                brand = 'Vapid',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'pol55',        name = 'Politie Audi',                brand = 'Vapid',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police2',       name = 'Politie VW Touran',                brand = 'Vapid',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police3',       name = 'Politie RangeRover',            brand = 'Vapid',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'police4',       name = 'Politie Undercover',              brand = 'Vapid',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'sheriff2',      name = 'Sheriff Cruiser',               brand = 'Vapid',           price = 100000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policeold1',    name = 'Kmar Ford',                brand = 'Declasse',        price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policeold2',    name = 'Kmar Bus',            brand = 'Albany',          price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policet',       name = 'Gevangenen Transport',            brand = 'Vapid',           price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'policeb',       name = 'Politie Motor',                   brand = 'Vapid',           price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'polmav',        name = 'Lifeliner',               brand = 'Buckingham',      price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'ambulance',     name = 'Ambulance',                     brand = 'Brute',           price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'firetruk',      name = 'Fire Truck',                    brand = 'MTL',             price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'lguard',        name = 'Lifeguard',                     brand = 'Declasse',        price = 110000,  category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'seashark2',     name = 'Seashark Lifeguard',            brand = 'Speedophile',     price = 40000,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'pranger',       name = 'Park Ranger',                   brand = 'Declasse',        price = 40000,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'fbi',           name = 'FIB Buffalo',                   brand = 'Bravado',         price = 40000,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'fbi2',          name = 'FIB Granger',                   brand = 'Declasse',        price = 40000,   category = 'emergency',      type = 'automobile', shop = 'none' },
    { model = 'predator',      name = 'Police Predator',               brand = 'Unknown',         price = 40000,   category = 'emergency',      type = 'automobile', shop = 'none' },
    --- Military (19)
    { model = 'vetir',         name = 'Vetir',                         brand = 'Unknown',         price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'kosatka',       name = 'Kosatka',                       brand = 'Rune',            price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'minitank',      name = 'RC Tank',                       brand = 'Unknown',         price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'scarab',        name = 'Scarab',                        brand = 'HVY',             price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'terbyte',       name = 'Terrorbyte',                    brand = 'Benefactor',      price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'thruster',      name = 'Thruster',                      brand = 'Mammoth',         price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'khanjali',      name = 'TM-02 Khanjali Tank',           brand = 'Unknown',         price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'chernobog',     name = 'Chernobog',                     brand = 'HVY',             price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'barrage',       name = 'Barrage',                       brand = 'HVY',             price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'trailerlarge',  name = 'Mobile Operations Center',      brand = 'Unknown',         price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'halftrack',     name = 'Half-track',                    brand = 'Bravado',         price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'apc',           name = 'APC Tank',                      brand = 'HVY',             price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'trailersmall2', name = 'Anti-Aircraft Trailer',         brand = 'Vom Feuer',       price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'rhino',         name = 'Rhino Tank',                    brand = 'Unknown',         price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'crusader',      name = 'Crusader',                      brand = 'Canis',           price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'barracks',      name = 'Barracks',                      brand = 'HVY',             price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'barracks2',     name = 'Barracks Semi',                 brand = 'HVY',             price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    { model = 'barracks3',     name = 'Barracks',                      brand = 'HVY',             price = 100000,  category = 'military',       type = 'automobile', shop = 'none' },
    --- Commercial (20)
    { model = 'pounder2',      name = 'Pounder Custom',                brand = 'MTL',             price = 55000,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'mule4',         name = 'Mule Custom',                   brand = 'Maibatsu',        price = 40000,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'phantom3',      name = 'Phantom Custom',                brand = 'Jobuilt',         price = 110000,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'hauler2',       name = 'Hauler Custom',                 brand = 'Jobuilt',         price = 100000,  category = 'commercial',     type = 'automobile', shop = 'truck' },

    { model = 'mule5',         name = 'Mule (Heist)',                  brand = 'Maibatsu',        price = 40000,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'stockade',      name = 'Stockade',                      brand = 'Brute',           price = 100000,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'pounder',       name = 'Pounder',                       brand = 'MTL',             price = 55000,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'phantom',       name = 'Phantom',                       brand = 'Jobuilt',         price = 100000,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'packer',        name = 'Packer',                        brand = 'MTL',             price = 100000,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'mule',          name = 'Mule',                          brand = 'Maibatsu',        price = 40000,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'hauler',        name = 'Hauler',                        brand = 'Jobuilt',         price = 100000,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'biff',          name = 'Biff',                          brand = 'Brute',           price = 100000,  category = 'commercial',     type = 'automobile', shop = 'truck' },
    { model = 'benson',        name = 'Benson',                        brand = 'Vapid',           price = 55000,   category = 'commercial',     type = 'automobile', shop = 'truck' },
    --motoren
    { model = 'apd750',        name = 'Apd750',                        brand = 'aprilia',         price = 18000,   category = 'aprilia',     type = 'automobile', shop = 'motor' },
    { model = 'rsv4',          name = 'Rsv4',                          brand = 'aprilia',         price = 18250,   category = 'aprilia',     type = 'automobile', shop = 'motor' },
    { model = 'aprt',          name = 'Aprt',                          brand = 'aprilia',         price = 17950,   category = 'aprilia',     type = 'automobile', shop = 'motor' },
    { model = 'aprsv4',          name = 'Aprsv4',                      brand = 'aprilia',         price = 18750,   category = 'aprilia',     type = 'automobile', shop = 'motor' },
    { model = 'apsxv',          name = 'Apsxv',                        brand = 'aprilia',         price = 17650,   category = 'aprilia',     type = 'automobile', shop = 'motor' },
    { model = 'bimota',        name = 'Bimota',                        brand = 'bimota',          price = 19500,   category = 'bimota',     type = 'automobile', shop = 'motor' },
    { model = 'bmws',            name = 'BMW S1000 RR 2014',           brand = 'BMW',             price = 20540,   category = 'BMW',     type = 'automobile', shop = 'motor' },
    { model = 'bmws1',           name = 'BMW S1000 RR 2014',           brand = 'BMW',             price = 20650,   category = 'BMW',     type = 'automobile', shop = 'motor' },
    { model = 'bmwrr',           name = 'BMW S1000 RR 2014',           brand = 'BMW',             price = 20560,   category = 'BMW',     type = 'automobile', shop = 'motor' },
    { model = 'bmwsr',           name = 'BMW 1100R Street Racer',      brand = 'BMW',             price = 20950,   category = 'BMW',     type = 'automobile', shop = 'motor' },
    { model = 'bmwsr',           name = 'BMW 1100R Street Racer',      brand = 'BMW',             price = 21000,   category = 'BMW',     type = 'automobile', shop = 'motor' },
    { model = 'bmwsrn',           name = 'BMW 1100R Naked Street Racer',  brand = 'BMW',          price = 21250,   category = 'BMW',     type = 'automobile', shop = 'motor' },
    { model = 'bmwr11',           name = 'BMW R1100 R',  brand = 'BMW',                           price = 20750,   category = 'BMW',     type = 'automobile', shop = 'motor' },
    { model = 'p51',           name = 'Confederate P51 Combat',  brand = 'Confederate',           price = 17500,   category = 'Confederate',     type = 'automobile', shop = 'motor' },
    { model = 'd99',           name = 'Ducati 1199 Panigale',  brand = 'Ducati',                  price = 19950,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'd12',           name = 'Ducati 1299 Panigale',  brand = 'Ducati',                  price = 20115,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'ddrr',           name = 'Ducati Desmosedici RR',  brand = 'Ducati',                price = 20160,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'diavel',           name = 'Ducati Diavel 2014',  brand = 'Ducati',                 price = 20250,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'ddc',           name = 'Ducati Diavel Carbon',  brand = 'Ducati',                  price = 20340,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'dgp15',           name = 'Ducati GP15',  brand = 'Ducati',                         price = 20300,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'dgp215',           name = 'Ducati GP15 V2',  brand = 'Ducati',                     price = 20100,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'dhpm',           name = 'Ducati Hypermotard 2013',  brand = 'Ducati',              price = 20750,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'sxf450',           name = 'KTM 450 SX-F',  brand = 'KTM',                          price = 15250,   category = 'KTM',     type = 'automobile', shop = 'motor' },
    { model = 'ktmtrr',           name = 'KTM EXC 530 TRR',  brand = 'KTM',                       price = 15300,   category = 'KTM',     type = 'automobile', shop = 'motor' },
    { model = 'ktmpit',           name = 'KTM Pit Bike',  brand = 'KTM',                          price = 15200,   category = 'KTM',     type = 'automobile', shop = 'motor' },
    { model = 'ktmrc',           name = 'KTM RC 390 2014',  brand = 'KTM',                        price = 14950,   category = 'KTM',     type = 'automobile', shop = 'motor' },
    { model = 'ktmrc8',           name = 'KTM RC8 1190 R',  brand = 'KTM',                        price = 15250,   category = 'KTM',     type = 'automobile', shop = 'motor' },
    { model = 'mvaf',           name = 'MV Agusta F4 RR',  brand = 'MV Agusta',                   price = 16750,   category = 'MV Agusta',     type = 'automobile', shop = 'motor' },
    { model = 'mvab',           name = 'MV Agusta Brutale 800 Dragster RR',  brand = 'MV Agusta', price = 16500,   category = 'MV Agusta',     type = 'automobile', shop = 'motor' },
    { model = 'mvar',           name = 'MV Agusta Rivale 800',  brand = 'MV Agusta',              price = 16800,   category = 'MV Agusta',     type = 'automobile', shop = 'motor' },
    { model = 'nbike',           name = 'NordicGames Bike',  brand = 'NordicGames',               price = 17000,   category = 'NordicGames',     type = 'automobile', shop = 'motor' },
    { model = 'sban',           name = 'Suzuki Bandit 1250N',  brand = 'Suzuki',                  price = 15250,   category = 'Suzuki',     type = 'automobile', shop = 'motor' },
    { model = 'gsxr',           name = 'Suzuki GSX 1000 R',  brand = 'Suzuki',                    price = 14950,   category = 'Suzuki',     type = 'automobile', shop = 'motor' },
    { model = 'sgsxr',           name = 'Suzuki GSX 1000 R V2',  brand = 'Suzuki',                price = 14850,   category = 'Suzuki',     type = 'automobile', shop = 'motor' },
    { model = 'sgsx13',           name = 'Suzuki GSX 1300 R',  brand = 'Suzuki',                  price = 15170,   category = 'Suzuki',     type = 'automobile', shop = 'motor' },
    { model = 'srmz',           name = 'Suzuki RMZ 250 2015',  brand = 'Suzuki',                  price = 15200,   category = 'Suzuki',     type = 'automobile', shop = 'motor' },
    { model = 'srmz2',           name = 'Suzuki RMZ 250 2015 V2',  brand = 'Suzuki',              price = 15250,   category = 'Suzuki',     type = 'automobile', shop = 'motor' },
    { model = 'ss750',           name = 'Suzuki Srad 750',  brand = 'Suzuki',                     price = 14900,   category = 'Suzuki',     type = 'automobile', shop = 'motor' },
    { model = 'tmrs',           name = 'TM Racing Supermotard',  brand = 'TM Racing',             price = 15195,   category = 'TM Racing',     type = 'automobile', shop = 'motor' },
    { model = 'yfz68',           name = 'Yamaha FZ6 2008',  brand = 'Yamaha',                     price = 16500,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yfz6',           name = 'Yamaha FZ6',  brand = 'Yamaha',                           price = 16250,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yfz8',           name = 'Yamaha FZ8 2011',  brand = 'Yamaha',                      price = 16300,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'ym1',           name = 'Yamaha M1',  brand = 'Yamaha',                             price = 16350,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yml1',           name = 'Yamaha M1 V2',  brand = 'Yamaha',                         price = 17000,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yrd1',           name = 'Yamaha R1 2014',  brand = 'Yamaha',                       price = 16850,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yr1',           name = 'Yamaha R1 2014 V2',  brand = 'Yamaha',                     price = 17250,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yr15',           name = 'Yamaha R1 2015',  brand = 'Yamaha',                       price = 17100,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yr6',           name = 'Yamaha R6',  brand = 'Yamaha',                             price = 17350,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yss',           name = 'Yamaha Star Stryker 2012',  brand = 'Yamaha',              price = 17570,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'ymt10',           name = 'Yamaha MT10 2016',  brand = 'Yamaha',                    price = 16680,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'ytmax',           name = 'Yamaha TMAX 500',  brand = 'Yamaha',                     price = 17680,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yxj6',           name = 'Yamaha XJ6',  brand = 'Yamaha',                           price = 16500,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'xj6',           name = 'Yamaha XJ6-F V3',  brand = 'Yamaha',                       price = 16650,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yxt',           name = 'Yamaha XT 660',  brand = 'Yamaha',                         price = 17480,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yx660',           name = 'Yamaha XT 660 PMERJ',  brand = 'Yamaha',                 price = 16350,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'yzf',           name = 'Yamaha YZ250F',  brand = 'Yamaha',                         price = 17900,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'r3',           name = 'Yamaha YZF R3 R25 2015',  brand = 'Yamaha',                 price = 16760,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'r6',           name = 'Yamaha YZF R6 2015',  brand = 'Yamaha',                     price = 16580,   category = 'Yamaha',     type = 'automobile', shop = 'motor' },
    { model = 'ke400',           name = 'Kawasaki Eliminator 400SE',  brand = 'Kawasaki',         price = 15000,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'kgpz',           name = 'Kawasaki GPZ 1100',  brand = 'Kawasaki',                  price = 15350,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'kx450f',           name = 'Kawasaki KX450F',  brand = 'Kawasaki',                  price = 15780,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'knh2',           name = 'Kawasaki Ninja H2R',  brand = 'Kawasaki',                 price = 18250,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'knh22',           name = 'Kawasaki Ninja H2R V2',  brand = 'Kawasaki',             price = 18350,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'zx10',           name = 'Kawasaki Ninja ZX-10R 2014',  brand = 'Kawasaki',         price = 18680,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'knzx',           name = 'Kawasaki Ninja ZX-10R 2015',  brand = 'Kawasaki',         price = 19000,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'kz1000',           name = 'Kawasaki Z1000',  brand = 'Kawasaki',                   price = 15980,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'kza1000',           name = 'Kawasaki Z1000 V2',  brand = 'Kawasaki',               price = 16150,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'kz750',           name = 'Kawasaki Z750',  brand = 'Kawasaki',                     price = 15750,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'kz800',           name = 'Kawasaki Z800',  brand = 'Kawasaki',                     price = 15800,   category = 'Kawasaki',     type = 'automobile', shop = 'motor' },
    { model = 'dhpm',           name = 'Ducati Hypermotard 2013',  brand = 'Ducati',              price = 21250,   category = 'Ducati',     type = 'automobile', shop = 'motor' },
    { model = 'hdfb',           name = 'Harley Davidson Fat Boy Lo Vintage',  brand = 'Harley Davidson',     price = 25750,   category = 'Harley Davidson',     type = 'automobile', shop = 'motor' },
    { model = 'hdss',           name = 'Harley-Davidson FXSTS Springer Softail',  brand = 'Harley Davidson', price = 25890,   category = 'Harley Davidson',     type = 'automobile', shop = 'motor' },
    { model = 'hdkn',           name = 'Harley-Davidson Knucklehead',  brand = 'Harley Davidson',            price = 26000,   category = 'Harley Davidson',     type = 'automobile', shop = 'motor' },
    { model = 'hcb1000',           name = 'Honda CB 1000 R',  brand = 'Honda',                                price = 16750,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hcb18',           name = 'Honda CB 1800 Caffe Racer',  brand = 'Honda',                        price = 17000,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hcbr',           name = 'Honda CBR 1000 RR',  brand = 'Honda',                                 price = 16800,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'honcbr',           name = 'Honda CBR 1000 RR Fireblade',  brand = 'Honda',                     price = 16950,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hcbr600',           name = 'Honda CBR 600 RR 2007',  brand = 'Honda',                          price = 17150,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'honcb',           name = 'Honda CB 650 F',  brand = 'Honda',                                   price = 17175,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'honcbf',           name = 'Honda CB 650 F Pretona',  brand = 'Honda',                          price = 17200,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hf150',           name = 'Honda Fan 150 2010',  brand = 'Honda',                               price = 16650,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hor14',           name = 'Honda Hornet 2014',  brand = 'Honda',                                price = 16900,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hor600',           name = 'Honda Hornet 600F 2010',  brand = 'Honda',                          price = 17200,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hlcr',           name = 'Honda LCR',  brand = 'Honda',                                         price = 17250,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hmarc',           name = 'Honda Marc VDS',  brand = 'Honda',                                   price = 17300,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hnsr',           name = 'Honda NSR500 2T',  brand = 'Honda',                                   price = 16720,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hrc213',           name = 'Honda RC213V',  brand = 'Honda',                                    price = 17980,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hrcp213',           name = 'Honda RC213V v2',  brand = 'Honda',                                price = 16860,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hxre',           name = 'Honda XRE 300',  brand = 'Honda',                                     price = 17300,   category = 'Honda',     type = 'automobile', shop = 'motor' },
    { model = 'hfc250',           name = 'Husqvarna FC 250',  brand = 'Husqvarn',                             price = 16850,   category = 'Husqvarn',     type = 'automobile', shop = 'motor' },
    { model = 'hn900',           name = 'Husqvarna Nuda 900',  brand = 'Husqvarn',                            price = 16750,   category = 'Husqvarn',     type = 'automobile', shop = 'motor' },
    { model = 'hsmx',           name = 'Husqvarna SM-MX 450 Super Moto',  brand = 'Husqvarn',                 price = 16580,   category = 'Husqvarn',     type = 'automobile', shop = 'motor' },
    { model = 'hsmxe',           name = 'Husqvarna SM-MX 450 Enduro',  brand = 'Husqvarn',                    price = 16690,   category = 'Husqvarn',     type = 'automobile', shop = 'motor' },
    { model = 'hsmr',           name = 'Husqvarna SMR 610',  brand = 'Husqvarn',                              price = 16950,   category = 'Husqvarn',     type = 'automobile', shop = 'motor' },
}

for i = 1, #Vehicles do
    QBShared.Vehicles[Vehicles[i].model] = {
        spawncode = Vehicles[i].model,
        name = Vehicles[i].name,
        brand = Vehicles[i].brand,
        model = Vehicles[i].model,
        price = Vehicles[i].price,
        category = Vehicles[i].category,
        hash = joaat(Vehicles[i].model),
        type = Vehicles[i].type,
        shop = Vehicles[i].shop
    }
end